export const FieldTypes = {
  STRING: 'STRING_TYPE',
  NUMBER: 'NUMBER_TYPE',
  SELECT: 'SELECT',
  AUTO_COMPLETE: 'AUTO_COMPLETE',
  DATE: 'DATE',
  DATE_RANGE: 'DATE_RANGE',
  BOOLEAN: 'BOOLEAN',
  MULTI_SELECT: 'MULTI_SELECT'
} as const;
