export const mqttTopics = {
  CMS: 'notification/cms',
  ACCOUNT: 'notification/:accountId'
};

export const mqttCMDs = {
  DONE_CONVERT_AUDIO: 'CMD_DONE_CONVERT_AUDIO',
  DONE_CONVERT_VIDEO: 'CMD_DONE_CONVERT_VIDEO',
  DONE_PROCESS_SUBTITLE: 'CMD_DONE_PROCESS_SUBTITLE',
  NEW_USER_REPORT: 'CMD_NEW_USER_REPORT',
  REPLY_COMMENT: 'CMD_REPLY_COMMENT',
  SEND_NOTIFICATION: 'CMD_SEND_NOTIFICATION',
  TOXIC_COMMENT_LOCKED: 'CMD_TOXIC_COMMENT_LOCKED',
  VOTE_COMMENT: 'CMD_VOTE_COMMENT'
};
