export const ErrorCode = {
  // === Group error code ===
  GROUP_ERROR_NAME_EXIST: 'ERROR-GROUP-000',
  GROUP_ERROR_NOT_FOUND: 'ERROR-GROUP-001',
  GROUP_ERROR_IN_USED: 'ERROR-GROUP-002',

  // === GroupPermission error code ===
  GROUP_PERMISSION_ERROR_NOT_FOUND: 'ERROR-GROUP-PERMISSION-000',
  GROUP_PERMISSION_ERROR_NAME_EXIST: 'ERROR-GROUP-PERMISSION-001',

  // === Permission error code ===
  PERMISSION_ERROR_NAME_EXIST: 'ERROR-PERMISSION-000',
  PERMISSION_ERROR_CODE_EXIST: 'ERROR-PERMISSION-001',
  PERMISSION_ERROR_NOT_FOUND: 'ERROR-PERMISSION-002',

  // === Account error code ===
  ACCOUNT_ERROR_UNKNOWN: 'ERROR-ACCOUNT-0000',
  ACCOUNT_ERROR_USERNAME_EXIST: 'ERROR-ACCOUNT-0001',
  ACCOUNT_ERROR_NOT_FOUND: 'ERROR-ACCOUNT-0002',
  ACCOUNT_ERROR_WRONG_PASSWORD: 'ERROR-ACCOUNT-0003',
  ACCOUNT_ERROR_WRONG_HASH_RESET_PASS: 'ERROR-ACCOUNT-0004',
  ACCOUNT_ERROR_LOCKED: 'ERROR-ACCOUNT-0005',
  ACCOUNT_ERROR_OPT_INVALID: 'ERROR-ACCOUNT-0006',
  ACCOUNT_ERROR_LOGIN: 'ERROR-ACCOUNT-0007',
  ACCOUNT_ERROR_SOCIAL_LOGIN_FAIL: 'ERROR-ACCOUNT-ERROR-0008',
  ACCOUNT_ERROR_NOT_DELETE_SUPPER_ADMIN: 'ERROR-ACCOUNT-00014',
  ACCOUNT_ERROR_EMAIL_EXIST: 'ERROR-ACCOUNT-00015',
  ACCOUNT_ERROR_PHONE_EXIST: 'ERROR-ACCOUNT-00016',
  ACCOUNT_ERROR_NEW_PASSWORD_SAME_OLD_PASSWORD: 'ERROR-ACCOUNT-00017',

  USER_ERROR_NOT_FOUND: 'ERROR-USER-ERROR-0000',
  USER_ERROR_USERNAME_EXIST: 'ERROR-USER-ERROR-0002',
  USER_ERROR_PHONE_EXIST: 'ERROR-USER-ERROR-0003',
  USER_ERROR_EMAIL_EXIST: 'ERROR-USER-ERROR-0004',
  USER_ERROR_WRONG_PASSWORD: 'ERROR-USER-ERROR-0005',
  USER_ERROR_NEW_PASSWORD_SAME_OLD_PASSWORD: 'ERROR-USER-ERROR-0006',
  USER_ERROR_OTP_INVALID: 'ERROR-USER-ERROR-0007',
  USER_ERROR_RESEND_OTP_LIMIT: 'ERROR-USER-ERROR-0008',
  USER_ERROR_CONFIRM_PASSWORD_INVALID: 'ERROR-USER-ERROR-0009',

  // === Employee error code ===
  EMPLOYEE_ERROR_NOT_FOUND: 'ERROR-EMPLOYEE-ERROR-0000',
  EMPLOYEE_ERROR_USERNAME_EXIST: 'ERROR-EMPLOYEE-ERROR-0002',
  EMPLOYEE_ERROR_PHONE_EXIST: 'ERROR-EMPLOYEE-ERROR-0003',
  EMPLOYEE_ERROR_EMAIL_EXIST: 'ERROR-EMPLOYEE-ERROR-0004',
  EMPLOYEE_ERROR_WRONG_PASSWORD: 'ERROR-EMPLOYEE-ERROR-0005',
  EMPLOYEE_ERROR_NEW_PASSWORD_SAME_OLD_PASSWORD: 'ERROR-EMPLOYEE-ERROR-0006',

  // === Category error code ===
  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-ERROR-0000',
  CATEGORY_ERROR_NAME_EXIST: 'ERROR-CATEGORY-ERROR-0002',
  CATEGORY_ERROR_HAS_MOVIE: 'ERROR-CATEGORY-ERROR-0003',

  // === Person error code ===
  PERSON_ERROR_NOT_FOUND: 'ERROR-PERSON-ERROR-0000',
  PERSON_ERROR_MOVIE_PERSON_EXIST: 'ERROR-PERSON-ERROR-0001',
  PERSON_ERROR_NOT_HAVE_KIND: 'ERROR-PERSON-ERROR-0002',

  // === Video error code ===
  VIDEO_LIBRARY_ERROR_NOT_FOUND: 'ERROR-VIDEO-LIBRARY-ERROR-0000',
  VIDEO_LIBRARY_ERROR_NAME_EXIST: 'ERROR-VIDEO-LIBRARY-ERROR-0002',
  VIDEO_LIBRARY_ERROR_MOVIE_ITEM_EXIST: 'ERROR-VIDEO-LIBRARY-ERROR-0003',
  VIDEO_LIBRARY_ERROR_NO_SERVER_CONFIG: 'ERROR-VIDEO-LIBRARY-ERROR-0005',

  // === Movie error code ===
  MOVIE_ERROR_NOT_FOUND: 'ERROR-MOVIE-ERROR-0000',
  MOVIE_ERROR_SLUG_EXIST: 'ERROR-MOVIE-ERROR-0002',
  MOVIE_ERROR_HAS_ITEM: 'ERROR-MOVIE-ERROR-0003',

  // === Movie item error code ===
  MOVIE_ITEM_ERROR_NOT_FOUND: 'ERROR-MOVIE-ITEM-ERROR-0000',
  MOVIE_ITEM_ERROR_PARENT_REQUIRED: 'ERROR-MOVIE-ITEM-ERROR-0002',
  MOVIE_ITEM_ERROR_VIDEO_REQUIRED: 'ERROR-MOVIE-ITEM-ERROR-0003',
  MOVIE_ITEM_ERROR_KIND_INVALID: 'ERROR-MOVIE-ITEM-ERROR-0004',
  MOVIE_ITEM_ERROR_INVALID_REQUEST: 'ERROR-MOVIE-ITEM-ERROR-0005',
  MOVIE_ITEM_ERROR_LABEL_EXIST: 'ERROR-MOVIE-ITEM-ERROR-0006',
  MOVIE_ITEM_EXCEED_TOTAL_EXPISODE: 'ERROR-MOVIE-ITEM-ERROR-0007',

  // === App version error code ===
  APP_VERSION_ERROR_NOT_FOUND: 'ERROR-APP-VERSION-0000',
  APP_VERSION_ERROR_NAME_EXIST: 'ERROR-APP-VERSION-0001',
  APP_VERSION_ERROR_NOT_HAVE_LATEST_VERSION: 'ERROR-APP-VERSION-0002',

  // === Style error code ===
  STYLE_ERROR_NOT_FOUND: 'ERROR-STYLE-0000',
  STYLE_ERROR_TYPE_EXIST: 'ERROR-STYLE-0001',
  STYLE_ERROR_TYPE_NOT_HAVE_DEFAULT: 'ERROR-STYLE-0002',

  // === Collection error code ===
  COLLECTION_ERROR_NOT_FOUND: 'ERROR-COLLECTION-0000',
  COLLECTION_ERROR_NAME_EXIST: 'ERROR-COLLECTION-0001',

  // === Collection item error code ===
  COLLECTION_ITEM_ERROR_NOT_FOUND: 'ERROR-COLLECTION-ITEM-0000',
  COLLECTION_ITEM_ERROR_MOVIE_EXIST: 'ERROR-COLLECTION-ITEM-0001',
  COLLECTION_ITEM_ERROR_MAX_ITEM: 'ERROR-COLLECTION-ITEM-0002',

  // === Server config error code ===
  SERVER_CONFIG_ERROR_NOT_FOUND: 'ERROR-SERVER-CONFIG-0000',
  SERVER_CONFIG_ERROR_SERVER_NUMBER_EXISTED: 'ERROR-SERVER-CONFIG-0001',
  SERVER_CONFIG_ERROR_HOSTNAME_EXISTED: 'ERROR-SERVER-CONFIG-0002',
  SERVER_CONFIG_ERROR_IP_PORT_EXISTED: 'ERROR-SERVER-CONFIG-0003',
  SERVER_CONFIG_ERROR_UNAUTHORIZED: 'ERROR-SERVER-CONFIG-0004',
  SERVER_CONFIG_ERROR_USED_BY_VIDEO_LIBRARY: 'ERROR-SERVER-CONFIG-0005',

  // === Setting error code ===
  SETTING_ERROR_NOT_FOUND: 'ERROR-SETTING-0000',
  SETTING_ERROR_EXISTED_GROUP_NAME_AND_KEY_NAME: 'ERROR-SETTING-0001',

  // === Video library subtitle error code ===
  VIDEO_LIBRARY_SUBTITLE_ERROR_LANGUAGE_EXISTED:
    'ERROR-VIDEO-LIBRARY-SUBTITLE-0002'
};
